name: Deploy Astro to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Config repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Config Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # 3. Install pnpm globally
      - name: Install pnpm
        run: npm install -g pnpm

      # 4. Cache pnpm dependencies
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      # 5. Install dependencies with pnpm
      - name: Install dependencies
        run: pnpm install

      # 6. Compile Astro
      - name: Build Astro
        run: pnpm run build

      # 7. Deploy
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1